version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  script-engine-service:
    image: behavox-script-engine:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_SERVER_DOMAIN=myrul.com
        - GF_SMTP_ENABLED=true
        - GF_SMTP_HOST=smtp.gmail.com:587
        - GF_SMTP_USER=myadrress@gmail.com
        - GF_SMTP_PASSWORD=mypassword
        - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

volumes:
  prometheus-data:
